import { LocationConfig, PrayerSetting, GlobalCalculationSettings, AudioTrackOption } from '../types';

export const DEFAULT_LOCATION: LocationConfig = {
  name: 'Madinah al-Munawwarah',
  country: 'Saudi Arabia',
  latitude: 24.4672,
  longitude: 39.6111,
  timezone: 'Asia/Riyadh',
  isAutoDetected: false,
};

export const PRESET_CITIES: LocationConfig[] = [
  {
    name: 'Madinah al-Munawwarah',
    country: 'Saudi Arabia',
    latitude: 24.4672,
    longitude: 39.6111,
    timezone: 'Asia/Riyadh',
    isAutoDetected: false,
  },
  {
    name: 'Makkah al-Mukarramah',
    country: 'Saudi Arabia',
    latitude: 21.4225,
    longitude: 39.8262,
    timezone: 'Asia/Riyadh',
    isAutoDetected: false,
  },
  {
    name: 'Jerusalem (Al-Quds)',
    country: 'Palestine',
    latitude: 31.7683,
    longitude: 35.2137,
    timezone: 'Asia/Jerusalem',
    isAutoDetected: false,
  },
  {
    name: 'Karachi',
    country: 'Pakistan',
    latitude: 24.8607,
    longitude: 67.0011,
    timezone: 'Asia/Karachi',
    isAutoDetected: false,
  },
  {
    name: 'Lahore',
    country: 'Pakistan',
    latitude: 31.5497,
    longitude: 74.3436,
    timezone: 'Asia/Karachi',
    isAutoDetected: false,
  },
  {
    name: 'Islamabad',
    country: 'Pakistan',
    latitude: 33.6844,
    longitude: 73.0479,
    timezone: 'Asia/Karachi',
    isAutoDetected: false,
  },
  {
    name: 'Cairo',
    country: 'Egypt',
    latitude: 30.0444,
    longitude: 31.2357,
    timezone: 'Africa/Cairo',
    isAutoDetected: false,
  },
  {
    name: 'Istanbul',
    country: 'Turkey',
    latitude: 41.0082,
    longitude: 28.9784,
    timezone: 'Europe/Istanbul',
    isAutoDetected: false,
  },
  {
    name: 'Dubai',
    country: 'United Arab Emirates',
    latitude: 25.2048,
    longitude: 55.2708,
    timezone: 'Asia/Dubai',
    isAutoDetected: false,
  },
  {
    name: 'London',
    country: 'United Kingdom',
    latitude: 51.5074,
    longitude: -0.1278,
    timezone: 'Europe/London',
    isAutoDetected: false,
  },
  {
    name: 'New York',
    country: 'United States',
    latitude: 40.7128,
    longitude: -74.0060,
    timezone: 'America/New_York',
    isAutoDetected: false,
  },
  {
    name: 'Toronto',
    country: 'Canada',
    latitude: 43.6532,
    longitude: -79.3832,
    timezone: 'America/Toronto',
    isAutoDetected: false,
  },
  {
    name: 'Kuala Lumpur',
    country: 'Malaysia',
    latitude: 3.1390,
    longitude: 101.6869,
    timezone: 'Asia/Kuala_Lumpur',
    isAutoDetected: false,
  },
  {
    name: 'Jakarta',
    country: 'Indonesia',
    latitude: -6.2088,
    longitude: 106.8456,
    timezone: 'Asia/Jakarta',
    isAutoDetected: false,
  },
  {
    name: 'Dhaka',
    country: 'Bangladesh',
    latitude: 23.8103,
    longitude: 90.4125,
    timezone: 'Asia/Dhaka',
    isAutoDetected: false,
  },
  {
    name: 'Sydney',
    country: 'Australia',
    latitude: -33.8688,
    longitude: 151.2093,
    timezone: 'Australia/Sydney',
    isAutoDetected: false,
  }
];

export const DEFAULT_AUDIO_TRACKS: AudioTrackOption[] = [
  {
    id: 'adhan_madina',
    name: 'Azan e Madinah',
    type: 'adhan',
    description: 'Serene prophetic call in Maqam Bayati style (Prophet\'s Mosque)',
    toneType: 'madina_adhan',
  },
  {
    id: 'adhan_makkah',
    name: 'Azan e Makkah (Haram)',
    type: 'adhan',
    description: 'Resonant and majestic call in Hijaz Maqam',
    toneType: 'makkah_adhan',
  },
  {
    id: 'adhan_fajr',
    name: 'Fajar Special Azan',
    type: 'adhan',
    description: 'Includes As-Salatu Khayrum-Minan-Nawm (Prayer is better than sleep)',
    toneType: 'fajr_adhan',
  },
  {
    id: 'adhan_soft',
    name: 'Soft Gentle Azan',
    type: 'adhan',
    description: 'Calm ambient acoustic tone suitable for home or office',
    toneType: 'soft_adhan',
  },
  {
    id: 'chime_tasbih',
    name: 'Tasbih Gentle Chime',
    type: 'reminder',
    description: 'Triple warm brass bell chime for voluntary prayers',
    toneType: 'chime_tasbih',
  },
  {
    id: 'chime_gentle',
    name: 'Dawn Spiritual Oud',
    type: 'reminder',
    description: 'Harmonic acoustic reminder for Ishraq, Chasht and Tahajjud',
    toneType: 'chime_gentle',
  },
  {
    id: 'bell_peaceful',
    name: 'Peaceful Sanctuary Bell',
    type: 'reminder',
    description: 'Soft reverberant meditation bell',
    toneType: 'bell_peaceful',
  },
];

export const DEFAULT_GLOBAL_SETTINGS: GlobalCalculationSettings = {
  method: 'Karachi',
  madhab: 'Hanafi',
  ishraqOffsetMinutes: 15, // Ishraq starts 15 min after sunrise by default
  highLatitudeRule: 'middle_of_the_night',
};

// Exactly the eight requested prayers
export const DEFAULT_PRAYERS: PrayerSetting[] = [
  {
    id: 'fajar',
    name: 'Fajar',
    arabicName: 'الفجر',
    category: 'obligatory',
    enabled: true,
    manualAdjustmentMinutes: 0,
    audioTrackId: 'adhan_fajr',
  },
  {
    id: 'ishraq',
    name: 'Ishraq',
    arabicName: 'الإشراق',
    category: 'voluntary',
    enabled: true,
    manualAdjustmentMinutes: 0,
    audioTrackId: 'chime_tasbih',
  },
  {
    id: 'chasht',
    name: 'Chasht',
    arabicName: 'الضحى',
    category: 'voluntary',
    enabled: true,
    manualAdjustmentMinutes: 0,
    audioTrackId: 'chime_gentle',
    chashtConfig: {
      mode: 'automatic',
      autoRule: 'midday',
      offsetMinutes: 90,
      manualTime: '09:15',
    },
  },
  {
    id: 'zohar',
    name: 'Zohar',
    arabicName: 'الظهر',
    category: 'obligatory',
    enabled: true,
    manualAdjustmentMinutes: 0,
    audioTrackId: 'adhan_madina',
  },
  {
    id: 'asar',
    name: 'Asar',
    arabicName: 'العصر',
    category: 'obligatory',
    enabled: true,
    manualAdjustmentMinutes: 0,
    audioTrackId: 'adhan_madina',
  },
  {
    id: 'maghrib',
    name: 'Maghrib',
    arabicName: 'المغرب',
    category: 'obligatory',
    enabled: true,
    manualAdjustmentMinutes: 0,
    audioTrackId: 'adhan_makkah',
  },
  {
    id: 'esha',
    name: 'Esha',
    arabicName: 'العشاء',
    category: 'obligatory',
    enabled: true,
    manualAdjustmentMinutes: 0,
    audioTrackId: 'adhan_madina',
  },
  {
    id: 'tahajjud',
    name: 'Tahajjud',
    arabicName: 'التهجد',
    category: 'voluntary',
    enabled: true,
    manualAdjustmentMinutes: 0,
    audioTrackId: 'bell_peaceful',
    tahajjudConfig: {
      mode: 'automatic',
      autoRule: 'last_third',
      manualTime: '02:45',
    },
  },
];
